#=======================================================================================================================
#== SPRING =============================================================================================================
#=======================================================================================================================

spring.profiles.active: default,local

server.port: 8090

logging:
  pattern:
    console: "%msg%n"
  level:
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
    com.nepc: DEBUG

#=======================================================================================================================
#== SPRING SECURITY ====================================================================================================
#=======================================================================================================================

security.basic.enabled: false
management.security.enabled: false
